/**
 * Site-wide SEO constants.
 *
 * `SITE_URL` is the canonical origin used for og:url, link rel=canonical and
 * every absolute URL in the JSON-LD schemas. The site has no custom domain
 * yet, so this is the Vercel production host. **When a real domain lands,
 * this constant plus the three static files in public/ (robots.txt,
 * llms.txt, sitemap.xml) all need updating** — those files can't import from
 * here, so they are the easy ones to forget. No trailing slash: callers
 * concatenate a path that always starts with one.
 */
export const SITE_URL = 'https://ksou-online-website-2026-qmolackhn.vercel.app';

export const SITE_NAME = 'KSOU Online';

export const SITE_LOCALE = 'en_IN';

/**
 * 1200×630 social card — the size every platform crops to. Generated by
 * scripts/generate-og-image.mjs from the real KSOU crest on brand blue;
 * re-run that script rather than editing the PNG by hand.
 */
export const DEFAULT_OG_IMAGE = '/og-image.png';

/** Absolute URL for a site-relative path. */
export const absoluteUrl = (path = '/') => `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
